name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add GTest
      run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: CMake check of banking and tests
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build modules
      run: cmake --build ${{github.workspace}}/build

    - name: Run test
      run: ${{github.workspace}}/build/run_test

    - name: Make Coverage Process
      run: |
        cd ${{github.workspace}}/build
        lcov -o report.info -c -d . 

    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ${{github.workspace}}/build/report.info
        coveralls-endpoint: https://coveralls.io

    - name: End coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
